### ISSUE TITLE
Doesn't work with nested SCSS files

### ISSUE THREAD

**Issue by AchoArnold** [1000ch/atom-csscomb#9]
eg 

``` scss
nav {
  ul {
    margin: 0;
    padding: 0;
    list-style: none;
  }

  li { display: inline-block; }
  //Comment
  a {
    display: block;
    padding: 6px 12px;
    text-decoration: none;
  }
}
```

Gets combed to 

``` css
nav {
    ul
    {
        margin: 0;
    padding: 0;
    list-style: none;
}

li {
    display: inline-block;
}
    //Comment
    a {
    display: block;
    padding: 6px 12px;
    text-decoration: none;
}
}
```

Possible duplicate of https://github.com/1000ch/atom-csscomb/issues/7
I am using  version **1.6.3** on Atom version **1.0.5**

**Comment by 1000ch** [comment]
@najela 
You say "combed but not formatted"?
I will fix it within today.

**Comment by AchoArnold** [comment]
@1000ch  You Rock :+1:

**Comment by 1000ch** [comment]
@najela Try newest? (But now, indent option is not applied. It forces 2 spaces indent.)

**Comment by AchoArnold** [comment]
@1000ch I've tried the new updated version of this package but I the error is still there.

**Comment by 1000ch** [comment]
@najela It worked with following `.scss`.

``` scss
nav {
  ul {
    margin: 0;
    padding: 0;
    list-style: none;
  }

  li { display: inline-block; }
  //Comment
  a {
    display: block;
    padding: 6px 12px;
    text-decoration: none;
  }
}
```

Would you try again after restarting Atom?
or put error logs if you have.

**Comment by AchoArnold** [comment]
After restarting atom, I got the following output

``` scss
nav {

  ul {
    margin: 0;
    padding: 0;
    list-style: none;
  }

  li {
    display: inline-block;
  }

  //Comment
    a {
    display: block;
    padding: 6px 12px;
    text-decoration: none;
  }
}
```

My normal indentation setting is 4 spaces but I see this is not being respected

``` cson
  "atom-csscomb":
    indentSize: 4
```

Also the general indentation is wrong.
